spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ventas?serverTimezone=UTC
    username: pablo
    password: 21001
    
#configuracion oracle

# jpa:
#   database: ORACLE
#   show-sql: true
#   hibernate:
#     ddl-auto: update
#   properties:
#     hibernate:
#       jdbc:
#         lob:non_contextual_creation:true
#           
# datasource:
#   driver-class-name: oracle.jdbc.OracleDriver
#   url: jdbc:oracle:thin:@localhost:1521:orcl
#   username: SYSTEM
#   password: Oracle2019  
     
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
