spring:

    
#Agregado para el manejo de imagenes, a quien corresponda crear producto esta configuracion le servira
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
      
#Agregando para el Envio de Correos Electronicos
  mail:
    host: smtp.gmail.com
            
        
#configuracion oracle
  jpa:
   database: ORACLE
   show-sql: true
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
      jdbc:
         lob:non_contextual_creation:true
           
  datasource:
   driver-class-name: oracle.jdbc.OracleDriver
   url: jdbc:oracle:thin:@localhost:1521:orcl
   username: SYSTEM
   password: Oracle2019
